services:
  - type: web
    name: amarFood
    runtime: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
